package practice.leetcode.easy;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class $389FindTheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "acebd"));
        System.out.println(findTheDifference2("abcd", "acebd"));
    }

    /**
     * their amazing solution of this problem
     * @param s
     * @param t
     * @return
     */
    static char findTheDifference2(String s, String t) {
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    /**
     * my solution of this problem
     * @param s
     * @param t
     * @return
     */
    static char findTheDifference(String s, String t) {
        int[] words = new int[26];
        for (int i=0;i<s.length();i++) {
            words[s.charAt(i)-'a']++;
            words[t.charAt(i)-'a']--;
        }
        words[t.charAt(t.length()-1)-'a']--;
        for (int i=0;i<words.length;i++) {
            if (words[i] < 0) return (char)(i+'a');
        }
        return ' ';
    }
}
